name: Update EPIC Earth Image

on:
  schedule:
    - cron: '0 9 * * *'  # 5 AM EST = 9 AM UTC
  workflow_dispatch:

jobs:
  update-daily-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to update image and README
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: |
          echo "✅ Running epic_daily.py..."
          python scripts/epic_daily.py

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Daily update: $(date -u +'%Y-%m-%d')"
          git push
