name: Daily EPIC Update

on:
  schedule:
    - cron: '0 10 * * *'  # 10:00 UTC = 5:00 AM EST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run EPIC Update Script
        run: python update_epic.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'you@example.com'
          git add .
          git commit -m "Daily EPIC update" || true
          git push
